ground_truth_publisher:
  update_rate: 200.0
  mocap_rate: 100.0 # This must match the mocap frame rate or velocity estimates will be mis-scaled
  velocity_smoothing_weight: 0.5
  mocap_dropout_threshold: 0.1 # s