jobs:
  build-melodic:
    working_directory: /catkin_ws/src
    docker:
      - image: ros:melodic-ros-core-bionic
    steps:
      - checkout
      - run:
          command: |
            sudo apt update
            sudo apt install -y build-essential
            sudo apt install -y ros-melodic-tf python-rosdep python-rosinstall python-rosinstall-generator python-wstool
      - run:
          command: |
            source /opt/ros/melodic/setup.bash
            catkin_init_workspace
            chmod +x setup.sh
            ./setup.sh
            cd ..
            catkin_make
workflows:
  version: 2
  build-and-test:
    jobs:
      - build-melodic:
          filters:
            branches:
              only:
                - master
                - develop
                - melodic-devel