jobs:
  build-melodic:
    working_directory: /catkin_ws/src
    docker:
      - image: ros:melodic-ros-base-bionic
    steps:
      - checkout
      - run:
          command: |
            sudo apt update
            source /opt/ros/melodic/setup.bash
            catkin_init_workspace
            chmod +x setup.sh
            ./setup.sh
            cd ..
            catkin_make
workflows:
  version: 2
  build-and-test:
    jobs:
      - build-melodic:
          filters:
            branches:
              only:
                - main
                - circleci-editor/circleci-project-setup
                - circleci-project-setup