axis_linear1: 1
axis_linear2: 0
axis_linear3: 7
scale_linear: 0.7
scale_linear_turbo: 1.5

axis_angular1: 4
axis_angular2: 3
axis_angular3: 6
scale_angular: 0.4

enable_button: 4  # L2 shoulder button
enable_turbo_button: 5  # L1 shoulder button
